package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;
/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "商品ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "商品类型", required = true)
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.quantity
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "商品数量", required = true)
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "商品价格（支持两位小数）", required = true)
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.image_path
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "商品图片路径", required = false)
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    public Goods(Integer id, String goodsType, Integer quantity, Float price, String imagePath, String title, String description, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.goodsType = goodsType;
        this.quantity = quantity;
        this.price = price;
        this.imagePath = imagePath;
        this.title = title;
        this.description = description;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    public Goods() {
        super();
    }
}