package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class OfficialContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案内容ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.official_document_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案ID", required = true)
    private Integer officialDocumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_content.content_address
     *
     * @mbggenerated
     */
    @ApiModelProperty(hidden = true)
    private String contentAddress;

    public OfficialContent(Integer id, Integer officialDocumentId, String contentAddress) {
        this.id = id;
        this.officialDocumentId = officialDocumentId;
        this.contentAddress = contentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_content
     *
     * @mbggenerated
     */
    public OfficialContent() {
        super();
    }
}