package edu.uestc.cilab.entity;

import edu.uestc.cilab.constant.DateConstant;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;
/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class OfficialDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.official_box_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书档案盒子id",required = true)
    private Integer officialBoxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.box_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "档号（原盒号）",required = true)
    private String boxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文号（原档案编号可以不填）")
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.title
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "题名",required = true)
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.page_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "页数",required = true)
    private String pageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.responsible_person
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "责任人",required = true)
    private String responsiblePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.keep_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "保管期限",required = true,allowableValues = "永久,100年,50年,30年,10年,长期,短期")
    @NotNull(message = "保管期限不能为空")
    private String keepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.document_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件日期",required = true)
    private String documentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.create_user_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "录入员",required = true)
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.gmt_create
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATE_PATTERN)
    @ApiModelProperty(hidden = true)
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column official_document.gmt_modified
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATE_PATTERN)
    @ApiModelProperty(hidden = true)
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table official_document
     *
     * @mbggenerated
     */
    public OfficialDocument() {
        super();
    }
}