package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class ProjectContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_content.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "工程档案内容ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_content.project_document_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "工程档案ID", required = true)
    private Integer projectDocumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_content.content_address
     *
     * @mbggenerated
     */
    @ApiModelProperty(hidden = true)
    private String contentAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_content
     *
     * @mbggenerated
     */
    public ProjectContent() {
        super();
    }
}