package edu.uestc.cilab.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class ProjectBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_box.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "工程档案盒子ID，添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_box.project_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "项目名称", required = true)
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_box.box_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "盒号", required = true)
    private String boxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_box.total_number
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件总数", required = false)
    private Integer totalNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_box
     *
     * @mbggenerated
     */
    public ProjectBox() {
        super();
    }
}