package edu.uestc.cilab.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import edu.uestc.cilab.constant.DateConstant;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiParam;
import lombok.Generated;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;
/**
 * @author: zhangfeng
 * @date: 2019-04-11 13:48
 * @description:
 **/
@Setter
@Getter
@ToString
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    @ApiParam(value = "id,添加时无需指定")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.number
     *
     * @mbggenerated
     */
    @ApiParam(value = "账号", required = true)
    @NotNull(message = "账号不能为空")
    @Length(min = 1, max = 20, message = "账号请控制在1-20字符")
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    @ApiParam(value = "password")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated
     */
    @ApiParam(value = "姓名", required = true)
    @NotNull(message = "姓名不能为空")
    @Length(min = 1, max = 40, message = "姓名请控制在1-40字符")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATETIME_PATTERN)
    @ApiParam(hidden = true)
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = DateConstant.DATETIME_PATTERN)
    @ApiParam(hidden = true)
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.enable
     *
     * @mbggenerated
     */
    @ApiParam(hidden = true)
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbggenerated
     */
    @JsonIgnore
    @ApiParam(hidden = true)
    private String salt;

    public User(Integer id, String number, String password, String name, Date gmtCreate, Date gmtModified, Boolean enable, String salt) {
        this.id = id;
        this.number = number;
        this.password = password;
        this.name = name;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.enable = enable;
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

}